FROM mcr.microsoft.com/dotnet/aspnet:8.0 as base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

ARG GITHUB_USER
ARG GITHUB_TOKEN
ENV GITHUB_USER=$GITHUB_USER
ENV GITHUB_TOKEN=$GITHUB_TOKEN

RUN dotnet nuget add source "https://nuget.pkg.github.com/Momentum-Labs-LLC/index.json" --name github --username ${GITHUB_USER} --password ${GITHUB_TOKEN} --store-password-in-clear-text

WORKDIR /src
COPY /src .
WORKDIR /src/Momentum.Analytics.Lambda.Api
RUN dotnet build Momentum.Analytics.Lambda.Api.csproj -c Release -o /app/build

FROM build as publish
RUN dotnet publish Momentum.Analytics.Lambda.Api.csproj -c Release -o /app/publish

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "Momentum.Analytics.Lambda.Api.dll" ]
