version: '3.8'
services:
  dddc-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dddc-dynamodb
    ports:
      - "9876:8000"
    volumes:
      - ./data:/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    healthcheck:
      test: ["CMD-SHELL", '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]']
      interval: 10s
      timeout: 10s
      retries: 10
  dynamodb-local-setup:
    depends_on:
      dddc-dynamodb:
        condition: service_healthy 
    image: amazon/aws-cli
    volumes:
      - "./src/Momentum.Analytics.DynamoDb/Schemas:/tmp/dynamo"
    environment:
      AWS_ACCESS_KEY_ID: 'FAKEID'
      AWS_SECRET_ACCESS_KEY: 'FAKEKEY'
      AWS_REGION: 'us-east-1'
    entrypoint:
      - bash
    command:
      #'-c "for f in PageViews PiiValues CollectedPii Visits FieldChanges; do aws dynamodb delete-table --endpoint-url "http://odddc-dynamodb:8000" --table-name $${f}; done"'
      '-c "for f in /tmp/dynamo/*.json; do aws dynamodb create-table --endpoint-url "http://dddc-dynamodb:8000" --cli-input-json file://"$${f#./}"; done"'

    